### ISSUE TITLE
Error in package.json

### ISSUE THREAD

**Issue by rbonillajr** [engcfraposo/nestjs-azure-service-bus#8]
Hello when I use the library and compile the application I get this error.

(node:387) [DEP0128] DeprecationWarning: Invalid 'main' field in '/repository/node_modules/nestjs-azure-service-bus/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by engcfraposo** [comment]
Thanks a lot, I'll create fix this and will deplot another version

**Comment by engcfraposo** [comment]
This deprecation solved at v0.0.16
